name: Deploy Flet Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Cambia a la versión de Python que necesitas

      # Instala las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      # Construye la aplicación para web
      - name: Build Flet app for web
        run: |
          flet pack main.py --web  # Asegúrate de que `main.py` es tu archivo principal

      # Publica en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Flet generará los archivos en `dist/`
